# Generated by Django 3.1.5 on 2021-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0002_auto_20210117_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='your_email@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Add your bio', max_length=500),
        ),
    ]
